// Overrides: what `argocd app set` changes on an Application, read into a
// form and written back as a patch -- the target revision, Helm's parameters,
// values, value files and release name, and Kustomize's images, replicas,
// name prefix and suffix and namespace.
//
// It also answers the question that decides whether an override is worth
// making at all: who owns this Application? One generated by an
// ApplicationSet is rewritten by it; one that is a child in an app of apps is
// put back by its parent when the parent syncs. An override made there is
// gone within minutes, and the place to make it is the owner.
//
// No drawing here: the panels draw (overrides-panel.js, appset-panel.js).
(function () {
    'use strict';

    var TRACKING_ANNOTATION = 'argocd.argoproj.io/tracking-id';
    var INSTANCE_LABEL = 'app.kubernetes.io/instance';

    function clone(v) {
        return v === undefined ? undefined : JSON.parse(JSON.stringify(v));
    }

    function arr(v) {
        return Array.isArray(v) ? v : [];
    }

    function str(v) {
        return v === undefined || v === null ? '' : String(v);
    }

    // ----- sources ---------------------------------------------------------------

    /**
     * An Application's sources, one or several: `spec.source`, or the list in
     * `spec.sources`. spec is the Application's spec -- or an ApplicationSet
     * template's.
     */
    function sourcesOf(spec) {
        spec = spec || {};
        if (Array.isArray(spec.sources) && spec.sources.length) return { multi: true, list: spec.sources };
        return { multi: false, list: spec.source ? [spec.source] : [] };
    }

    /** What a source is called in a tab: its chart, or its path, or its repo. */
    function sourceLabel(source, index) {
        if (!source) return 'Source ' + (index + 1);
        if (source.chart) return source.chart + (source.targetRevision ? ' ' + source.targetRevision : '');
        if (source.ref && !source.path) return 'ref: ' + source.ref;
        var repo = str(source.repoURL).replace(/^https?:\/\//, '').replace(/\.git$/, '');
        return (repo.split('/').slice(-1)[0] || 'source') + (source.path ? '/' + source.path.replace(/^\.\/?/, '') : '');
    }

    /**
     * Which tool renders a source, as far as can be told: what Argo CD
     * reported, else what the source itself says. A Helm chart from a Helm
     * repository has a chart; a git path could be anything until Argo CD has
     * looked.
     */
    function sourceType(source, reported) {
        if (reported) return reported;
        if (!source) return '';
        if (source.chart || source.helm) return 'Helm';
        if (source.kustomize) return 'Kustomize';
        if (source.plugin) return 'Plugin';
        if (source.directory) return 'Directory';
        return '';
    }

    /** The form one source is edited as. Every field present, whatever the source has. */
    function readSource(source, reported) {
        source = source || {};
        var helm = source.helm || {};
        var kustomize = source.kustomize || {};
        return {
            type: sourceType(source, reported),
            targetRevision: str(source.targetRevision),
            helm: {
                releaseName: str(helm.releaseName),
                valueFiles: arr(helm.valueFiles).map(str),
                parameters: arr(helm.parameters).map(function (p) {
                    return { name: str(p.name), value: str(p.value), forceString: !!p.forceString };
                }),
                values: str(helm.values),
                // valuesObject is structured YAML the page has no way to edit
                // as text without a YAML parser; it is shown, and the editor
                // is offered for it.
                valuesObject: helm.valuesObject === undefined ? null : helm.valuesObject,
            },
            kustomize: {
                images: arr(kustomize.images).map(str),
                replicas: arr(kustomize.replicas).map(function (r) {
                    return { name: str(r.name), count: str(r.count) };
                }),
                namePrefix: str(kustomize.namePrefix),
                nameSuffix: str(kustomize.nameSuffix),
                namespace: str(kustomize.namespace),
            },
        };
    }

    /** Sets or removes one field: an empty value or list is no field at all. */
    function put(obj, key, value) {
        var empty = value === '' || value === null || value === undefined || (Array.isArray(value) && !value.length);
        if (empty) delete obj[key];
        else obj[key] = value;
    }

    function pruned(obj) {
        return obj && Object.keys(obj).length ? obj : undefined;
    }

    /**
     * The source with the form written into it. Everything the form does not
     * cover -- repoURL, path, chart, a Helm option like skipCrds, a Kustomize
     * patch -- is carried over untouched.
     */
    function writeSource(original, form) {
        var out = clone(original) || {};
        put(out, 'targetRevision', form.targetRevision.trim());

        var helm = clone(out.helm) || {};
        put(helm, 'releaseName', form.helm.releaseName.trim());
        put(
            helm,
            'valueFiles',
            form.helm.valueFiles
                .map(function (f) {
                    return f.trim();
                })
                .filter(Boolean),
        );
        put(
            helm,
            'parameters',
            form.helm.parameters
                .filter(function (p) {
                    return p.name.trim();
                })
                .map(function (p) {
                    var param = { name: p.name.trim(), value: p.value };
                    if (p.forceString) param.forceString = true;
                    return param;
                }),
        );
        put(helm, 'values', form.helm.values.trim() ? form.helm.values : '');
        if (pruned(helm)) out.helm = helm;
        else delete out.helm;

        var kustomize = clone(out.kustomize) || {};
        put(
            kustomize,
            'images',
            form.kustomize.images
                .map(function (i) {
                    return i.trim();
                })
                .filter(Boolean),
        );
        put(
            kustomize,
            'replicas',
            form.kustomize.replicas
                .filter(function (r) {
                    return r.name.trim();
                })
                .map(function (r) {
                    // A count is an int-or-string in Argo CD's API; a plain
                    // number goes as a number.
                    var n = r.count.trim();
                    return { name: r.name.trim(), count: /^\d+$/.test(n) ? Number(n) : n };
                }),
        );
        put(kustomize, 'namePrefix', form.kustomize.namePrefix.trim());
        put(kustomize, 'nameSuffix', form.kustomize.nameSuffix.trim());
        put(kustomize, 'namespace', form.kustomize.namespace.trim());
        if (pruned(kustomize)) out.kustomize = kustomize;
        else delete out.kustomize;
        return out;
    }

    // ----- patches -----------------------------------------------------------------

    function isObject(v) {
        return v !== null && typeof v === 'object' && !Array.isArray(v);
    }

    /**
     * The JSON merge patch (RFC 7386) that turns before into after: a key only
     * in before becomes null, an object is diffed inside, anything else that
     * differs is sent whole -- a list included, which is how a merge patch
     * treats one. Undefined when they are the same.
     */
    function mergeDiff(before, after) {
        if (JSON.stringify(before) === JSON.stringify(after)) return undefined;
        if (!isObject(before) || !isObject(after)) return after === undefined ? null : clone(after);
        var out = {};
        Object.keys(before).forEach(function (k) {
            if (!(k in after)) out[k] = null;
        });
        Object.keys(after).forEach(function (k) {
            var d = mergeDiff(before[k], after[k]);
            if (d !== undefined) out[k] = d;
        });
        return Object.keys(out).length ? out : undefined;
    }

    /**
     * The patch that writes edited sources back. spec is where the sources
     * live now; at is the path to it from the object's root: ['spec'] for an
     * Application, ['spec', 'template', 'spec'] for an ApplicationSet.
     *
     * Several sources go back as the whole list, since a merge patch cannot
     * change one item of a list; one goes back as a diff of itself, so a field
     * somebody else changed meanwhile is not written over.
     */
    function patchFor(spec, at, edited) {
        var current = sourcesOf(spec);
        var inner;
        if (current.multi) {
            inner = JSON.stringify(current.list) === JSON.stringify(edited) ? undefined : { sources: clone(edited) };
        } else {
            var d = mergeDiff(current.list[0] || {}, edited[0] || {});
            inner = d === undefined ? undefined : { source: d };
        }
        if (inner === undefined) return null;
        for (var i = at.length - 1; i >= 0; i--) {
            var wrap = {};
            wrap[at[i]] = inner;
            inner = wrap;
        }
        return inner;
    }

    /**
     * What an edit changes, in words, for the review under the form: one line
     * per field that differs.
     */
    function describeChanges(before, after, label) {
        var lines = [];
        var prefix = label ? label + ': ' : '';
        function list(v) {
            return arr(v).length ? arr(v).join(', ') : 'none';
        }
        if (before.targetRevision !== after.targetRevision) {
            lines.push(prefix + 'target revision ' + (before.targetRevision || 'default') + ' → ' + (after.targetRevision || 'default'));
        }
        var bp = {};
        before.helm.parameters.forEach(function (p) {
            bp[p.name] = p;
        });
        var ap = {};
        after.helm.parameters.forEach(function (p) {
            if (p.name.trim()) ap[p.name.trim()] = p;
        });
        Object.keys(ap).forEach(function (n) {
            if (!bp[n]) lines.push(prefix + 'set ' + n + '=' + ap[n].value);
            else if (bp[n].value !== ap[n].value || bp[n].forceString !== ap[n].forceString) {
                lines.push(prefix + n + ' ' + bp[n].value + ' → ' + ap[n].value);
            }
        });
        Object.keys(bp).forEach(function (n) {
            if (!ap[n]) lines.push(prefix + 'remove parameter ' + n);
        });
        if (before.helm.releaseName !== after.helm.releaseName.trim()) {
            lines.push(prefix + 'release name ' + (before.helm.releaseName || 'default') + ' → ' + (after.helm.releaseName.trim() || 'default'));
        }
        var bf = before.helm.valueFiles.join('\n');
        var af = after.helm.valueFiles.map(function (f) { return f.trim(); }).filter(Boolean).join('\n');
        if (bf !== af) lines.push(prefix + 'value files ' + list(before.helm.valueFiles) + ' → ' + list(af ? af.split('\n') : []));
        if (before.helm.values.trim() !== after.helm.values.trim()) lines.push(prefix + 'values changed');
        var bi = before.kustomize.images.join('\n');
        var ai = after.kustomize.images.map(function (i) { return i.trim(); }).filter(Boolean).join('\n');
        if (bi !== ai) lines.push(prefix + 'images ' + list(before.kustomize.images) + ' → ' + list(ai ? ai.split('\n') : []));
        var br = JSON.stringify(before.kustomize.replicas);
        var ar = JSON.stringify(after.kustomize.replicas.filter(function (r) { return r.name.trim(); }));
        if (br !== ar) lines.push(prefix + 'replicas changed');
        ['namePrefix', 'nameSuffix', 'namespace'].forEach(function (k) {
            if (before.kustomize[k] !== after.kustomize[k].trim()) {
                lines.push(prefix + k + ' ' + (before.kustomize[k] || 'none') + ' → ' + (after.kustomize[k].trim() || 'none'));
            }
        });
        return lines;
    }

    // ----- who owns it ------------------------------------------------------------------

    /**
     * The Application an app of apps put this one there from, by Argo CD's own
     * record of it: the tracking annotation ("parent:argoproj.io/Application:
     * ns/name"), or, under label tracking, the instance label naming the
     * parent. Null when nothing says so -- which is most Applications.
     */
    function parentOf(app, apps) {
        var meta = app.metadata || {};
        var annotations = meta.annotations || {};
        var labels = meta.labels || {};
        var parentName = '';
        var tracking = annotations[TRACKING_ANNOTATION] || '';
        if (tracking) parentName = tracking.split(':')[0];
        else if (labels[INSTANCE_LABEL] && labels[INSTANCE_LABEL] !== meta.name) parentName = labels[INSTANCE_LABEL];
        if (!parentName || parentName === meta.name) return null;
        var found = arr(apps).filter(function (a) {
            return a.metadata && a.metadata.name === parentName && a.metadata.name !== meta.name;
        })[0];
        return found || { metadata: { name: parentName, namespace: meta.namespace }, spec: {}, missing: true };
    }

    function selfHeals(app) {
        var auto = app && app.spec && app.spec.syncPolicy && app.spec.syncPolicy.automated;
        return !!auto && !!auto.selfHeal;
    }

    /**
     * Whether an ApplicationSet leaves the source alone on the Applications it
     * makes: its ignoreApplicationDifferences naming /spec/source or
     * /spec/sources, or a path under them.
     */
    function appsetIgnoresSources(appset) {
        return arr(appset && appset.spec && appset.spec.ignoreApplicationDifferences).some(function (rule) {
            return arr(rule.jsonPointers).some(function (p) {
                return /^\/spec\/sources?(\/|$)/.test(p);
            }) || arr(rule.jqPathExpressions).some(function (p) {
                return /^\.spec\.sources?\b/.test(p);
            });
        });
    }

    /**
     * Who owns an Application, and what that means for an override made on it
     * directly:
     *
     *   { kind: 'appset', name, namespace, reverts, text }
     *   { kind: 'parent', name, namespace, reverts, text }
     *   { kind: '', reverts: false, text }
     */
    function ownerOf(app, apps, appsets) {
        var meta = app.metadata || {};
        var byAppset = arr(meta.ownerReferences).filter(function (o) {
            return o.kind === 'ApplicationSet';
        })[0];
        if (byAppset) {
            var appset = arr(appsets).filter(function (s) {
                return s.metadata && s.metadata.name === byAppset.name;
            })[0];
            var keeps = appsetIgnoresSources(appset);
            var policy = appset && appset.spec && appset.spec.syncPolicy && appset.spec.syncPolicy.applicationsSync;
            var createOnly = policy === 'create-only' || policy === 'create-delete';
            return {
                kind: 'appset',
                name: byAppset.name,
                namespace: meta.namespace,
                reverts: !keeps && !createOnly,
                text: keeps
                    ? 'Made by ApplicationSet ' + byAppset.name + ', which is set to leave this Application’s source alone, so an override here stays.'
                    : createOnly
                      ? 'Made by ApplicationSet ' + byAppset.name + ', which only creates its Applications (' + policy + ') and does not update them, so an override here stays.'
                      : 'Made by ApplicationSet ' + byAppset.name + ', which rewrites it from its template: an override made here is undone on its next pass. Make it in the ApplicationSet instead.',
            };
        }
        var parent = parentOf(app, apps);
        if (parent) {
            var heals = selfHeals(parent);
            var name = parent.metadata.name;
            return {
                kind: 'parent',
                name: name,
                namespace: parent.metadata.namespace || meta.namespace,
                missing: !!parent.missing,
                reverts: heals,
                text: heals
                    ? 'Deployed by the Application ' + name + ' (app of apps), which heals itself: an override made here is put back to what is in Git within minutes. Change it in Git, or in ' + name + '’s own source.'
                    : 'Deployed by the Application ' + name + ' (app of apps). An override made here makes ' + name + ' OutOfSync, and its next sync puts it back. Change it in Git, or in ' + name + '’s own source, to keep it.',
            };
        }
        return { kind: '', reverts: false, text: '' };
    }

    // ----- ApplicationSet generators --------------------------------------------------------

    /**
     * What an ApplicationSet's generators feed its template, as far as can be
     * read without running them: a list generator's elements, and the kind
     * of each other generator. Matrix and merge generators are named with
     * what they combine.
     */
    function generatorsOf(appset) {
        return arr(appset && appset.spec && appset.spec.generators).map(function describe(g) {
            var kind = Object.keys(g).filter(function (k) {
                return k !== 'selector';
            })[0] || 'unknown';
            var body = g[kind] || {};
            var out = { kind: kind, elements: [], parts: [], note: '' };
            if (kind === 'list') {
                out.elements = arr(body.elements).map(function (e) {
                    return isObject(e) ? e : { value: e };
                });
                if (body.elementsYaml) out.note = 'Elements come from a template (elementsYaml).';
            } else if (kind === 'matrix' || kind === 'merge') {
                out.parts = arr(body.generators).map(describe);
            } else if (kind === 'git') {
                out.note = (body.repoURL || '') + (body.revision ? ' @ ' + body.revision : '') +
                    (arr(body.files).length ? ' · files ' + body.files.map(function (f) { return f.path; }).join(', ') : '') +
                    (arr(body.directories).length ? ' · directories ' + body.directories.map(function (d) { return d.path; }).join(', ') : '');
            } else if (kind === 'clusters') {
                out.note = body.selector ? 'Clusters matching a selector' : 'Every cluster Argo CD knows';
                if (body.values) out.elements = [body.values];
            }
            return out;
        });
    }

    window.ArgoOverrides = {
        sourcesOf: sourcesOf,
        sourceLabel: sourceLabel,
        sourceType: sourceType,
        readSource: readSource,
        writeSource: writeSource,
        mergeDiff: mergeDiff,
        patchFor: patchFor,
        describeChanges: describeChanges,
        parentOf: parentOf,
        ownerOf: ownerOf,
        selfHeals: selfHeals,
        generatorsOf: generatorsOf,
    };
})();
