// Which plugins the app carries a mark for, and where it is.
//
// A plugin that is installed is drawn with the logo file it ships (see
// PluginMark). These are for the moment before that: an offer in the sidebar
// or in Settings is a plugin with no files on this machine yet, and it is
// exactly then -- choosing between ten of them -- that a mark does the most
// work. They are also the fallback for an installed plugin that ships none.
//
// Each file is a copy of what the matching plugin ships, which for a plugin
// about a real product is that project's own logo, taken from where the
// project publishes it. Those are the projects' trademarks, and are used here
// only to name the plugin for each of them.
//
// The list is here rather than the drawings: asking for a mark this app does
// not have would be a request that 404s on every row, and knowing the answer
// first is cheaper than finding it out.
//
// Generated by cmd/pluginmarks -- do not edit by hand. Run it again after a
// plugin changes its logo. A copy going stale is harmless: the shipped file
// wins once that plugin is installed.

/** Plugin ids this app ships a mark for, as files under public/plugin-marks. */
const MARKED = new Set([
    // argocd, built into the app
    'argocd',
    // Calico
    'calico',
    // cert-manager
    'cert-manager',
    // Cilium
    'cilium',
    // Flannel
    'flannel',
    // flux, built into the app
    'flux',
    // Image inventory
    'image-inventory',
    // Kube-OVN
    'kubeovn',
    // KubeVirt
    'kubevirt',
    // Longhorn
    'longhorn',
    // MetalLB
    'metallb',
    // Optimization advisor
    'optimization',
    // prometheus, built into the app
    'prometheus',
    // Vitistack
    'vitistack',
]);

/** Where this app's own mark for a plugin is, or '' when it has none for it. */
export function markFor(id: string): string {
    return MARKED.has(id) ? `/plugin-marks/${id}.svg` : '';
}
