// Command pluginmarks regenerates frontend/src/lib/plugins/marks.ts from the
// logos the plugins ship.
//
//	go run ./cmd/pluginmarks ../k8sdockside-*
//
// The app draws an installed plugin with the logo file that plugin serves, so
// these copies are only for the moment before that: an offer in the sidebar or
// in Settings is a plugin with no files on this machine yet, and that is
// exactly when telling ten of them apart matters. A copy going stale is
// therefore harmless -- the shipped file always wins once the plugin is
// installed -- but there is no reason to leave it stale, and this is how it is
// refreshed.
//
// The copies are written as files under frontend/public, not built into the
// bundle: a logo is an illustration, and one of these is 74 KB on its own.
// As files they are fetched only when one is actually drawn, and each is
// parsed as a document of its own, which is what keeps a gradient id or a
// <style> rule in one logo from reaching into another. The generated
// TypeScript is only the list of which ids have one.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const (
	listing = "frontend/src/lib/plugins/marks.ts"
	// Served at /plugin-marks/<id>.svg. Everything in public is copied to the
	// site root as it is, so the address is the same in the desktop app and
	// in server mode, and stays the same between builds.
	assets = "frontend/public/plugin-marks"
)

const header = `// Which plugins the app carries a mark for, and where it is.
//
// A plugin that is installed is drawn with the logo file it ships (see
// PluginMark). These are for the moment before that: an offer in the sidebar
// or in Settings is a plugin with no files on this machine yet, and it is
// exactly then -- choosing between ten of them -- that a mark does the most
// work. They are also the fallback for an installed plugin that ships none.
//
// Each file is a copy of what the matching plugin ships, which for a plugin
// about a real product is that project's own logo, taken from where the
// project publishes it. Those are the projects' trademarks, and are used here
// only to name the plugin for each of them.
//
// The list is here rather than the drawings: asking for a mark this app does
// not have would be a request that 404s on every row, and knowing the answer
// first is cheaper than finding it out.
//
// Generated by cmd/pluginmarks -- do not edit by hand. Run it again after a
// plugin changes its logo. A copy going stale is harmless: the shipped file
// wins once that plugin is installed.

/** Plugin ids this app ships a mark for, as files under public/plugin-marks. */
const MARKED = new Set([
`

type manifest struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Logo string `json:"logo"`
	UI   *struct {
		Dir string `json:"dir"`
	} `json:"ui"`
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		_, _ = fmt.Fprintln(stderr, "usage: pluginmarks <plugin folder> ...")
		_, _ = fmt.Fprintln(stderr, "Writes "+assets+" and "+listing+" from the logo each plugin ships.")
		return 2
	}

	type mark struct {
		id, name string
		svg      []byte
	}
	var marks []mark
	var failed bool

	for _, dir := range args {
		raw, err := os.ReadFile(filepath.Join(dir, "plugin.json")) // #nosec G304,G703 -- the folders being read are this command's arguments, named by whoever runs it
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "%s: %v\n", dir, err)
			failed = true
			continue
		}
		var m manifest
		if err := json.Unmarshal(raw, &m); err != nil {
			_, _ = fmt.Fprintf(stderr, "%s: %v\n", dir, err)
			failed = true
			continue
		}
		// A plugin without a logo is not an error: it falls back to its icon,
		// and there is simply nothing to carry for it.
		if m.Logo == "" {
			_, _ = fmt.Fprintf(stdout, "%-16s no logo, skipped\n", m.ID)
			continue
		}
		uiDir := "ui"
		if m.UI != nil && m.UI.Dir != "" {
			uiDir = m.UI.Dir
		}
		svg, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(uiDir), filepath.FromSlash(m.Logo))) // #nosec G304,G703 -- same folder, and the path within it is the manifest's own logo field
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "%s: %v\n", m.ID, err)
			failed = true
			continue
		}
		// Drawn through <img>, so it is parsed as XML: anything without a
		// viewBox will not scale, and the page would show a broken image
		// rather than an error.
		if !strings.Contains(string(svg), "viewBox=") {
			_, _ = fmt.Fprintf(stderr, "%s: its logo has no viewBox, so it will not scale\n", m.ID)
			failed = true
			continue
		}
		marks = append(marks, mark{m.ID, m.Name, svg})
	}
	if failed {
		return 1
	}
	slices.SortFunc(marks, func(a, b mark) int { return strings.Compare(a.id, b.id) })

	// Written fresh each time, so a plugin that loses its logo loses its file
	// here too rather than leaving one nothing points at.
	if err := os.RemoveAll(assets); err != nil {
		_, _ = fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}
	if err := os.MkdirAll(assets, 0o750); err != nil {
		_, _ = fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}

	var out strings.Builder
	out.WriteString(header)
	var bytes int
	for _, m := range marks {
		if err := os.WriteFile(filepath.Join(assets, m.id+".svg"), m.svg, 0o600); err != nil {
			_, _ = fmt.Fprintf(stderr, "%v\n", err)
			return 1
		}
		bytes += len(m.svg)
		fmt.Fprintf(&out, "    // %s\n    '%s',\n", m.name, m.id)
	}
	out.WriteString(`]);

/** Where this app's own mark for a plugin is, or '' when it has none for it. */
export function markFor(id: string): string {
    return MARKED.has(id) ? ` + "`/plugin-marks/${id}.svg`" + ` : '';
}
`)

	if err := os.WriteFile(listing, []byte(out.String()), 0o600); err != nil {
		_, _ = fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}
	_, _ = fmt.Fprintf(stdout, "\nwrote %s and %d files in %s (%d bytes of drawing)\n", listing, len(marks), assets, bytes)
	return 0
}
