// Command pluginmarks regenerates frontend/src/lib/plugins/marks.ts from the
// logos the plugins ship.
//
//	go run ./cmd/pluginmarks ../*/
//
// The app draws an installed plugin with the logo file that plugin serves, so
// these copies are only for the moment before that: an offer in the sidebar or
// in Settings is a plugin with no files on this machine yet, and that is
// exactly when telling ten of them apart matters. A copy going stale is
// therefore harmless -- the shipped file always wins once the plugin is
// installed -- but there is no reason to leave it stale, and this is how it is
// refreshed.
//
// The copies are written as files under frontend/public, not built into the
// bundle: a logo is an illustration, and one of these is 74 KB on its own.
// As files they are fetched only when one is actually drawn, and each is
// parsed as a document of its own, which is what keeps a gradient id or a
// <style> rule in one logo from reaching into another. The generated
// TypeScript is only the list of which ids have one.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const (
	listing = "frontend/src/lib/plugins/marks.ts"
	// Served at /plugin-marks/<id>.<ext>. Everything in public is copied to the
	// site root as it is, so the address is the same in the desktop app and
	// in server mode, and stays the same between builds.
	assets = "frontend/public/plugin-marks"
)

const header = `// Which plugins the app carries a mark for, and where it is.
//
// A plugin that is installed is drawn with the logo file it ships (see
// PluginMark). These are for the moment before that: an offer in the sidebar
// or in Settings is a plugin with no files on this machine yet, and it is
// exactly then -- choosing between ten of them -- that a mark does the most
// work. They are also the fallback for an installed plugin that ships none.
//
// Each file is a copy of what the matching plugin ships, which for a plugin
// about a real product is that project's own logo, taken from where the
// project publishes it. Those are the projects' trademarks, and are used here
// only to name the plugin for each of them.
//
// The list is here rather than the drawings: asking for a mark this app does
// not have would be a request that 404s on every row, and knowing the answer
// first is cheaper than finding it out.
//
// Generated by cmd/pluginmarks -- do not edit by hand. Run it again after a
// plugin changes its logo. A copy going stale is harmless: the shipped file
// wins once that plugin is installed.

/** Plugin ids this app ships a mark for, and its file under public/plugin-marks. */
const MARKED = new Map<string, string>([
`

// markTypes are the formats a mark may be copied in -- the same as a plugin's
// logo may be (internal/plugins.LogoTypes).
var markTypes = []string{".svg", ".png", ".webp"}

type manifest struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Logo string `json:"logo"`
	UI   *struct {
		Dir string `json:"dir"`
	} `json:"ui"`
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		_, _ = fmt.Fprintln(stderr, "usage: pluginmarks <plugin folder> ...")
		_, _ = fmt.Fprintln(stderr, "Writes "+assets+" and "+listing+" from the logo each plugin ships.")
		return 2
	}

	type mark struct {
		id, name, ext string
		data          []byte
	}
	var marks []mark
	var dropped []string
	var failed bool

	for _, dir := range args {
		raw, err := os.ReadFile(filepath.Join(dir, "plugin.json")) // #nosec G304,G703 -- the folders being read are this command's arguments, named by whoever runs it
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "%s: %v\n", dir, err)
			failed = true
			continue
		}
		var m manifest
		if err := json.Unmarshal(raw, &m); err != nil {
			_, _ = fmt.Fprintf(stderr, "%s: %v\n", dir, err)
			failed = true
			continue
		}
		// A plugin without a logo is not an error: it falls back to its icon.
		// Any mark left here from when it had one is dropped, so the listing
		// never points at something the plugin no longer has.
		if m.Logo == "" {
			dropped = append(dropped, m.ID)
			_, _ = fmt.Fprintf(stdout, "%-16s no logo\n", m.ID)
			continue
		}
		uiDir := "ui"
		if m.UI != nil && m.UI.Dir != "" {
			uiDir = m.UI.Dir
		}
		ext := strings.ToLower(filepath.Ext(m.Logo))
		if !slices.Contains(markTypes, ext) {
			_, _ = fmt.Fprintf(stderr, "%s: its logo %s is not %s\n", m.ID, m.Logo, strings.Join(markTypes, ", "))
			failed = true
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(uiDir), filepath.FromSlash(m.Logo))) // #nosec G304,G703 -- same folder, and the path within it is the manifest's own logo field
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "%s: %v\n", m.ID, err)
			failed = true
			continue
		}
		if msg := undrawable(ext, data); msg != "" {
			_, _ = fmt.Fprintf(stderr, "%s: its logo %s\n", m.ID, msg)
			failed = true
			continue
		}
		marks = append(marks, mark{m.ID, m.Name, ext, data})
	}
	if failed {
		return 1
	}
	slices.SortFunc(marks, func(a, b mark) int { return strings.Compare(a.id, b.id) })

	if err := os.MkdirAll(assets, 0o750); err != nil {
		_, _ = fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}

	// Only the folders named on the command line are touched. The built-in
	// plugins -- Argo CD, Flux, Prometheus -- ship inside the app and have no
	// repository to be read from, so their marks live here as ordinary assets
	// and have to survive a run that knows nothing about them.
	named := map[string]string{}
	var size int
	for _, m := range marks {
		// A plugin that changed its logo's format leaves no copy in the old
		// one behind, which would otherwise list the id twice.
		if err := removeMark(m.id); err != nil {
			_, _ = fmt.Fprintf(stderr, "%v\n", err)
			return 1
		}
		if err := os.WriteFile(filepath.Join(assets, m.id+m.ext), m.data, 0o600); err != nil {
			_, _ = fmt.Fprintf(stderr, "%v\n", err)
			return 1
		}
		named[m.id] = m.name
		size += len(m.data)
	}
	for _, id := range dropped {
		if err := removeMark(id); err != nil {
			_, _ = fmt.Fprintf(stderr, "%v\n", err)
			return 1
		}
	}

	files, err := onDisk(assets)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}

	var out strings.Builder
	out.WriteString(header)
	for _, file := range files {
		id := strings.TrimSuffix(file, filepath.Ext(file))
		if name := named[id]; name != "" {
			fmt.Fprintf(&out, "    // %s\n", name)
		} else {
			fmt.Fprintf(&out, "    // %s, built into the app\n", id)
		}
		fmt.Fprintf(&out, "    ['%s', '%s'],\n", id, file)
	}
	out.WriteString(`]);

/** Where this app's own mark for a plugin is, or '' when it has none for it. */
export function markFor(id: string): string {
    const file = MARKED.get(id);
    return file ? ` + "`/plugin-marks/${file}`" + ` : '';
}
`)

	if err := os.WriteFile(listing, []byte(out.String()), 0o600); err != nil {
		_, _ = fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}
	_, _ = fmt.Fprintf(stdout, "\nwrote %s: %d marks (%d refreshed, %d bytes of drawing)\n", listing, len(files), len(marks), size)
	return 0
}

// undrawable says why a logo would not draw through <img>, or nothing.
func undrawable(ext string, data []byte) string {
	switch ext {
	case ".svg":
		// Parsed as XML: anything without a viewBox will not scale, and the
		// page would show a broken image rather than an error.
		if !bytes.Contains(data, []byte("viewBox=")) {
			return "has no viewBox, so it will not scale"
		}
	case ".png":
		// A file that went through a line-ending conversion loses the \r in
		// its signature and no longer decodes, so this is checked in full.
		if !bytes.HasPrefix(data, []byte("\x89PNG\r\n\x1a\n")) {
			return "is not a valid PNG"
		}
	case ".webp":
		if len(data) < 12 || string(data[:4]) != "RIFF" || string(data[8:12]) != "WEBP" {
			return "is not a valid WebP"
		}
	}
	return ""
}

// removeMark removes the copy of a plugin's mark in every format it may be in.
func removeMark(id string) error {
	for _, ext := range markTypes {
		if err := os.Remove(filepath.Join(assets, id+ext)); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

// onDisk is every mark file in the folder, sorted by id -- the ones just
// written and the ones that were already there.
func onDisk(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() || !slices.Contains(markTypes, strings.ToLower(filepath.Ext(e.Name()))) {
			continue
		}
		files = append(files, e.Name())
	}
	slices.SortFunc(files, func(a, b string) int {
		return strings.Compare(strings.TrimSuffix(a, filepath.Ext(a)), strings.TrimSuffix(b, filepath.Ext(b)))
	})
	return files, nil
}
